config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/dashboard" => "accounts#index"
  get "/profile/:username" => "accounts#profile", as: :profile
  post "follow/account" => "accounts#follow_account", as: :follow_account

  resources :posts, only: [:new, :create, :show]
  resources :comments, only: [:create]
  resources :posts do
    resources :likes
  end

  root to: "public#homepage"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include ImageUploader::Attachment.new(:image)

  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :followers

  def full_name
    "#{first_name} #{second_name}"
  end

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following
    Follower.where(following_id: self.id).count
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account
  validates_presence_of :comment
  validates_presence_of :account_id
  validates_presence_of :post_id
end

app/models/follower.rb
class Follower < ApplicationRecord
  # belongs_to :accounts
  validates_uniqueness_of :follower_id, scope: :following_id
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order created_at: :desc }
  include ImageUploader::Attachment.new(:image)
  belongs_to :account
  has_many :likes, dependent: :destroy
  has_many :comments
  before_create :set_active

  scope :active, -> { where active: true }

  def already_liked?
    Like.where(user_id: current_account.id, post_id:
      params[:post_id]).exists?
  end

  def total_likes
    0
  end

  private

  def set_active
    self.active = true
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_account, only: [:profile]

  def index
    @post = Post.active
    @comment = Comment.new
    following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
    following_ids << current_account.id
    @follower_suggestions = Account.where.not(id: following_ids)

  end

  def profile
    @posts = @account.posts.active
  end

  def follow_account
    follower_id = params[:follow_id]
    if Follower.create(follower_id: current_account.id, following_id: follower_id)
      flash[:success] = "Following"
    else
      flash[:danger] = "Uncompleted"
    end
    redirect_to dashboard_path
  end

  private

  def set_account
    @account = Account.find_by_username(params[:username])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :second_name, :image, :description, :website])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :second_name, :email, :password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_account!

  def create
    @comment = Comment.new(comment_params)
    @comment.account_id = current_account.id if account_signed_in?

    if @comment.save
      redirect_to dashboard_path, flash: { success: 'Completed' }
    else
      redirect_to dashboard_path, flash: { danger: 'Uncompleted!' }

    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id if account_signed_in?

    if @post.save
      redirect_to dashboard_path, flash: { success: 'Completed' }
    else
      redirect_to new_post_path, flash: { danger: 'Uncomplited!' }

    end
  end

  def like
    @post = Post.all.find(params)
    Like.create(account_id: current_account.id, post_id: @post.id)
    redirect_to post_path(@post)
  end

  def show
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :description)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def homepage
    
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def profile_picture account, width = 200
    # image_path = account.image.present? ? account.image.derivation_url(:thumbnail, 50, 50) : 'placeholder.webp'
    image_path = account.image.present? ? account.image.url : 'placeholder.webp'
    image_tag(image_path, width: width, class: 'img-circle')
  end

  def can_edit_profile? profile_id
    account_signed_in? && current_account.id == profile_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |account| %>
  <div class="recommended-follower">
    <div class="row">
      <div class="col-sm-3 col-2">
        <%= link_to profile_picture(account, 40), profile_path(account.username) %>
      </div>
      <div class="col-sm-9 col-10">
        <%= form_tag follow_account_path, method: :post, class: "float-end" do%>
        <%= hidden_field_tag :follow_id, account.id %>
          <%= submit_tag "Follow", class: "btn btn-secondary btn-sm" %>
        <% end %>
        <%= link_to account.username, profile_path(account.username), class: "text-dark" %>
        <p class="text-muted"><%= account.created_at < 5.days.ago ? "New" : "Old" %></p>
      </div>
    </div>
  </div>

<% end %>

app/views/accounts/index.html.erb
<head>
  <script src="https://kit.fontawesome.com/90b584e3b1.js" crossorigin="anonymous"></script>
</head>
<div class="container">
  <div class="row">
    <div class="col-8">
      <% @post.each do |post| %>
        <div class="inst-post">
          <div class="post-meta">
            <%= link_to image_tag(post.image.derivation_url(:thumbnail, 50, 50), class: "img-circle"), profile_path(post.account.username) %>
            <%= link_to post.account.username, profile_path(post.account.username), class: "text-dark" %>
          </div>


          <%= image_tag post.image.url, class: "img img-fluid" %>



          <div class="post-details">

            <% pre_like = post.likes.find { |like| like.account_id == current_account.id} %>
            <% if pre_like %>
              <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete %>
            <% else %>
              <%= button_to 'Like', post_likes_path(post), method: :post %>
            <% end %>


            <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
            <p>
              <strong><%= link_to post.account.username, profile_path(post.account.username), class: "text-dark" %></strong>
            </p>
            <%= simple_format post.description %>
            <p class="text-muted"><%= time_ago_in_words post.created_at %> ago</p>


            <%= render "posts/comments", post: post %>
          </div>
          <div class="comment-box">
            <%= form_for @comment do |f| %>
              <%= f.hidden_field :post_id, value: post.id %>
              <div class="input-group">
                <%= f.text_field :comment, placeholder: "Add your necessary opinion here...", class: "form-control post-comment" %>
                <div class="input-group-append">
                  <%= f.submit "Post", class: "btn btn-success float-end" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-4">
      <div class="account-summary">
        <p>
          <%= link_to (image_tag current_account.image.derivation_url(:thumbnail, 50, 50), class: "img-circle"), profile_path(current_account.username) if current_account.image.present? %>
          <strong><%= link_to current_account.username, profile_path(current_account.username) %></strong></p>

        <p><em><%= current_account.full_name %></em></p>
      </div>
      <div class="follower-suggestion">
        <%= link_to "View all", "#", class: "float-end" %>
        <p class="text-muted">Suggestions for you:</p>
        <%= render "accounts/follower_suggestions" %>

      </div>
    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">

      <%= profile_picture @account %>
    </div>
    <div class="col-8 text-start">
      <div class="col-6">
        <%= link_to "Edit", edit_account_registration_path, class: "btn btn-muted float-end" if can_edit_profile?(@account.id) %>
        <h1><%= @account.full_name %></h1>
      </div>
      <div class="profile-stats"><%= @account.posts.count %> posts</div>
      <div class="profile-stats"><%= @account.total_followers %> followers</div>
      <div class="profile-stats"><%= @account.total_following %> following</div>

      <p><%= @account.full_name %></p>
      <%= simple_format @account.description %>
      <p><%= link_to @account.website if @account.website.present? %></p>
    </div>
  </div>
  <div class="row profile-posts">
    <% @posts.each do |post| %>
      <div class="col-4">
        <div class="inst-post">
          <%= image_tag post.image.url, class: "img img-fluid" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_account_nav.html.erb
<li class="nav-item">
<%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
</li>
<li class="nav-item"><%= link_to "New Post", new_post_path, class: "nav-link" %></li>
<li class="nav-item"><%= link_to "Profile", profile_path(current_account.username), class: "nav-link" %></li>
<li class="nav-item"><%= button_to "Sign Out", destroy_account_session_path, method: :delete, class: "nav-link btn btn-danger" %></li>

app/views/layouts/_public_nav.html.erb
<!--<li class="nav-item"><a class="nav-link" href="#">Home</a></li>-->
<!--<li class="nav-item"><a class="nav-link" href="#!">About</a></li>-->
<!--<li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>-->
<!--<li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Blog</a></li>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script src="https://kit.fontawesome.com/90b584e3b1.js" crossorigin="anonymous"></script>
<html>

<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="styles.scss" rel="stylesheet"/>

  <title>CCI</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">


  <div class="container">
    <strong><a class="navbar-brand" href="/">
      <i class="fa-solid fa-poo-storm"></i>  //  CCI</a></strong>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if account_signed_in? %>
          <%= render "layouts/account_nav" %>
        <% else %>
          <%= render "layouts/public_nav" %>
        <% end %>
          </ul>
          </div>
          </div>
          </nav>
          <!-- Responsive navbar-->
          <div class="container">
            <div class="row">
              <div class="col-lg-12 ">
                <%= yield %>
              </div>
            </div>
          </div>
          <body>
          </body>
          </html>

app/views/posts/_comments.html.erb
<% post.comments.each do |comment| %>
  <div class="comment">
  <strong><%= comment.account.username %></strong>
  <%= comment.comment %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

  <div class="form-group">
  <div>
    <%= f.label :image, style: "display: block" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  </div>



  <div class="form-group">
  <%= f.label :description, class: "form-control" %>
  <%= f.text_area :description, class: "form-control" %>
  </div>

  <%= f.submit "Save Post", class: "btn btn-success" %>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= post.image %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @post.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>

    <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
  <% end %>
</div>



<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>